name: bramzo_lite
description: Bramzo Todo Application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  google_fonts:
  flutter_screenutil: ^5.4.0
  flutter_svg: ^1.0.0

  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1

  vibration: ^1.8.4
  audioplayers: ^5.2.1
  path_provider: ^2.0.11


  ensure_visible_when_focused: ^1.2.0
  animated_reorderable_list:
    path: ./animated_reorderable_list








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer:
  build_runner: ^2.3.3
  objectbox_generator:

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/svgs/
    - assets/sounds/




  # example:
  fonts:
    - family: consoles
      fonts:
        - asset: assets/fonts/CONSOLAB.TTF
    - family: cour
      fonts:
        - asset: assets/fonts/cour.ttf
    - family: BAHNSCHRIFT
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT.TTF




        # - asset: assets/fonts/cour.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
