// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'views/home/models/tab_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4332786457986493309),
      name: 'TabModel',
      lastPropertyId: const IdUid(6, 5682899577540989164),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7343973945499299942),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1679561170778430859),
            name: 'localId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 125993080908638395),
            name: 'value',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8765125468199737653),
            name: 'isCheckedOff',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5682899577540989164),
            name: 'index',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4332786457986493309),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [8788653164439878207],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TabModel: EntityDefinition<TabModel>(
        model: _entities[0],
        toOneRelations: (TabModel object) => [],
        toManyRelations: (TabModel object) => {},
        getId: (TabModel object) => object.id,
        setId: (TabModel object, int id) {
          object.id = id;
        },
        objectToFB: (TabModel object, fb.Builder fbb) {
          final valueOffset = fbb.writeString(object.value);
          fbb.startTable(7);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.localId);
          fbb.addOffset(2, valueOffset);
          fbb.addBool(3, object.isCheckedOff);
          fbb.addInt64(5, object.index);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TabModel(
              localId:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              index: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              value: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              isCheckedOff: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 10, false))
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TabModel] entity fields to define ObjectBox queries.
class TabModel_ {
  /// see [TabModel.id]
  static final id = QueryIntegerProperty<TabModel>(_entities[0].properties[0]);

  /// see [TabModel.localId]
  static final localId =
      QueryIntegerProperty<TabModel>(_entities[0].properties[1]);

  /// see [TabModel.value]
  static final value =
      QueryStringProperty<TabModel>(_entities[0].properties[2]);

  /// see [TabModel.isCheckedOff]
  static final isCheckedOff =
      QueryBooleanProperty<TabModel>(_entities[0].properties[3]);

  /// see [TabModel.index]
  static final index =
      QueryIntegerProperty<TabModel>(_entities[0].properties[4]);
}
